name: Java CI with Maven, Docker, Coveralls and SonarCloud in Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v6
      with:
        path: |
          ~/.m2
          ~/.sonar/cache
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
        restore-keys: ${{ runner.os }}-m2-

    - name: Set Maven Additional Goals
      run: echo "SONARGOAL=sonar:sonar" >> $GITHUB_ENV
      if: ${{ env.SONAR_TOKEN }}

    - name: Build with Maven, Coveralls and SonarCloud
      run: xvfb-run mvn verify -Pcoveralls $SONARGOAL
      working-directory: com.msohailse.app.incident
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Generate JUnit Report
      if: always()
      run: mvn surefire-report:report-only
      working-directory: com.msohailse.app.incident

    - name: Archive JUnit Report
      if: always()
      uses: actions/upload-artifact@v6
      with:
        name: surefire-report
        path: '**/target/reports'
